GET http://localhost:8082/api/v1/storage
Accept: application/json

###
POST http://localhost:8082/api/v1/storage
Content-Type: application/json

{
  "group_id": 0,
  "type": 1,
  "path": "focal-server-cloudimg-amd64-disk-kvm.img",
  "name": "ubuntu20.04 LTS CloudInit",
  "cloud_init": true,
  "min_cpu": 1,
  "min_mem": 512,
  "os": "",
  "admin": false
}

###
GET http://localhost:8082/api/v1/storage
Accept: application/json

###
